"""another migration

Revision ID: 524655e28c90
Revises: 9af8bcdaec87
Create Date: 2025-05-31 12:42:34.145208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524655e28c90'
down_revision = '9af8bcdaec87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_attributes')
    # ### end Alembic commands ###
