"""added weight and parent to product model

Revision ID: 9af8bcdaec87
Revises: 3717cb36f4b4
Create Date: 2025-05-03 06:29:30.918613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9af8bcdaec87'
down_revision = '3717cb36f4b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_product_parent', 'products', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_product_parent', type_='foreignkey')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('weight')

    # ### end Alembic commands ###
